export {default as Header} from './Header/Header'
export {default as Main} from './Main/Main'
export {default as Features} from './Features/Features'
export {default as EarlyAccess} from './EarlyAccess/EarlyAccess'
export {default as Documentations} from './Documentations/Documentations'
export {default as Footer} from './Footer/Footer'